#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# rst — xml-rpc-based ikiwiki plugin to process RST files
#
# based a little bit on rst.pm by Sergio Talens-Oliag, but only a little bit. :)
#
# Copyright © martin f. krafft <madduck@madduck.net>
# Released under the terms of the GNU GPL version 2
#
__name__ = 'rst'
__description__ = 'xml-rpc-based ikiwiki plugin to process RST files'
__version__ = '0.3'
__author__ = 'martin f. krafft <madduck@madduck.net>'
__copyright__ = 'Copyright © ' + __author__
__licence__ = 'GPLv2'

from docutils.core import publish_parts;
from proxy import IkiWikiProcedureProxy

def rst2html(proxy, *args):
    kwargs = _to_dict(args)
    parts = publish_parts(kwargs["content"],
                          writer_name="html",
                          settings_overrides = { 'halt_level': 6
                                               , 'file_insertion_enabled': 0
                                               , 'raw_enabled': 1
                                               })
    return '\n'.join(parts['html_body'].splitlines()[1:-1])

def _to_dict(args):
    # args is a list paired by key, value, so we turn it into a dict
    return dict((k, v) for k, v in zip(*[iter(args)]*2))

def getsetup(proxy, *kwargs):
    return 'plugin', { 'safe' : 1, 'rebuild' : 1 }

import sys
def debug(s):
    sys.stderr.write(__name__ + ':DEBUG:%s\n' % s)
    sys.stderr.flush()

proxy = IkiWikiProcedureProxy(__name__, debug_fn=None)
proxy.hook('getsetup', getsetup)
proxy.hook('htmlize', rst2html)
proxy.run()
